version: "2"
services:
  nginx:
      build: nginx
      networks:
        - lnmp
     # privileged: true
      ports:
        - "80:80"
        - "81:81"
        - "443:443"
      links:
        - "php-fpm"
      volumes:
            - /data/wwwroot/:/data/wwwroot/
            - /etc/localtime/:/etc/localtime/
            - /data/wwwlogs/:/data/wwwlogs/
            - /data/wwwroot/docker/nginx/vhost/:/etc/nginx/vhost/
            - /data/wwwroot/docker/nginx/ssl/:/etc/nginx/ssl/
            - /data/wwwroot/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  php-fpm:
      build: php-fpm
      networks:
        - lnmp
     # privileged: true
      ports:
        - "9000:9000"
        - "8282:8282"
      volumes:
            - /data/wwwroot/:/data/wwwroot/
            - /etc/localtime/:/etc/localtime/
            - /data/wwwlogs/:/data/wwwlogs/
            - /data/wwwroot/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - /data/wwwroot/docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
  mysql:
      image: "mysql:5.7"
      networks:
        - lnmp
      ports:
        - "3306:3306"
      volumes:
         - /var/lib/mysql/:/var/lib/mysql/
         - /etc/localtime/:/etc/localtime/
         - /data/wwwroot/docker/mysql/:/etc/mysql/
      environment:
          MYSQL_ROOT_PASSWORD: mysqlpasswd
  redis:
      image: "redis"
      networks:
        - lnmp
      volumes:
        - /etc/localtime/:/etc/localtime/
      ports:
        - "6379:6379"
networks:
  lnmp:
